//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NullGC.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NullGC.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC10_Description {
            get {
                return ResourceManager.GetString("NGC10_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type &apos;{0}&apos; will be boxed to &apos;{1}&apos; at runtime.
        /// </summary>
        internal static string NGC10_MessageFormat {
            get {
                return ResourceManager.GetString("NGC10_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type will be boxed.
        /// </summary>
        internal static string NGC10_Title {
            get {
                return ResourceManager.GetString("NGC10_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC11_Description {
            get {
                return ResourceManager.GetString("NGC11_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINQ struct &apos;{0}&apos; will be boxed to &apos;{1}&apos; at runtime.
        /// </summary>
        internal static string NGC11_MessageFormat {
            get {
                return ResourceManager.GetString("NGC11_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINQ chain will be boxed.
        /// </summary>
        internal static string NGC11_Title {
            get {
                return ResourceManager.GetString("NGC11_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC12_Description {
            get {
                return ResourceManager.GetString("NGC12_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specific overload of Linq operator &apos;{0}&apos; is not implemented yet, the LINQ chain will be boxed at runtime to be able to use as an IEnumerable.
        /// </summary>
        internal static string NGC12_MessageFormat {
            get {
                return ResourceManager.GetString("NGC12_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This LINQ operator overload is not implemented.
        /// </summary>
        internal static string NGC12_Title {
            get {
                return ResourceManager.GetString("NGC12_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC20_Description {
            get {
                return ResourceManager.GetString("NGC20_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow() or Take() should be called on IExplicitOwnership`1 typed argument when being passed by value.
        /// </summary>
        internal static string NGC20_MessageFormat {
            get {
                return ResourceManager.GetString("NGC20_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow() or Take() should be called when passed by value.
        /// </summary>
        internal static string NGC20_Title {
            get {
                return ResourceManager.GetString("NGC20_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC21_Description {
            get {
                return ResourceManager.GetString("NGC21_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can specify either Owned or Borrowed attribute but not both.
        /// </summary>
        internal static string NGC21_MessageFormat {
            get {
                return ResourceManager.GetString("NGC21_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict explicit ownership attributes.
        /// </summary>
        internal static string NGC21_Title {
            get {
                return ResourceManager.GetString("NGC21_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC22_Description {
            get {
                return ResourceManager.GetString("NGC22_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow() or Take() should be called on IExplicitOwnership`1 typed value that assigns to `ref` or `out` parameter.
        /// </summary>
        internal static string NGC22_MessageFormat {
            get {
                return ResourceManager.GetString("NGC22_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow() or Take() should be called on `ref` or `out` parameter.
        /// </summary>
        internal static string NGC22_Title {
            get {
                return ResourceManager.GetString("NGC22_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC23_Description {
            get {
                return ResourceManager.GetString("NGC23_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow() or Take() should be called on return value that is IExplicitOwnership`1 typed.
        /// </summary>
        internal static string NGC23_MessageFormat {
            get {
                return ResourceManager.GetString("NGC23_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow() or Take() should be called on return value.
        /// </summary>
        internal static string NGC23_Title {
            get {
                return ResourceManager.GetString("NGC23_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC24_Description {
            get {
                return ResourceManager.GetString("NGC24_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ownership kind of source of assignment &apos;{0}&apos; is incompatible with the target of assignment &apos;{1}&apos;.
        /// </summary>
        internal static string NGC24_MessageFormat {
            get {
                return ResourceManager.GetString("NGC24_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible ownership kind between source and target of assignment.
        /// </summary>
        internal static string NGC24_Title {
            get {
                return ResourceManager.GetString("NGC24_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC25_Description {
            get {
                return ResourceManager.GetString("NGC25_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The callee can potentially call Dispose() on the IExplicitOwnership`1 typed argument, thus either examine the callee&apos;s behavior carefully to ensure no Dispose() will be called or make the ownership explicit by calling Borrow()/Take() or Tag the argument value with ownership attributes.
        /// </summary>
        internal static string NGC25_MessageFormat {
            get {
                return ResourceManager.GetString("NGC25_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential double-free situation if the callee may call Dispose() on argument value.
        /// </summary>
        internal static string NGC25_Title {
            get {
                return ResourceManager.GetString("NGC25_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC26_Description {
            get {
                return ResourceManager.GetString("NGC26_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership of some return path(s) in the method body are not explicitly specified.
        /// </summary>
        internal static string NGC26_MessageFormat {
            get {
                return ResourceManager.GetString("NGC26_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership of some return path(s) are not explicitly specified.
        /// </summary>
        internal static string NGC26_Title {
            get {
                return ResourceManager.GetString("NGC26_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC27_Description {
            get {
                return ResourceManager.GetString("NGC27_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all return paths have the same ownership kind..
        /// </summary>
        internal static string NGC27_MessageFormat {
            get {
                return ResourceManager.GetString("NGC27_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all return paths have the same ownership kind..
        /// </summary>
        internal static string NGC27_Title {
            get {
                return ResourceManager.GetString("NGC27_Title", resourceCulture);
            }
        }
    }
}
