//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NullGC.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NullGC.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC10_Description {
            get {
                return ResourceManager.GetString("NGC10_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type &apos;{0}&apos; will be boxed to &apos;{1}&apos; at runtime.
        /// </summary>
        internal static string NGC10_MessageFormat {
            get {
                return ResourceManager.GetString("NGC10_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type will be boxed.
        /// </summary>
        internal static string NGC10_Title {
            get {
                return ResourceManager.GetString("NGC10_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC11_Description {
            get {
                return ResourceManager.GetString("NGC11_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINQ struct &apos;{0}&apos; will be boxed to &apos;{1}&apos; at runtime.
        /// </summary>
        internal static string NGC11_MessageFormat {
            get {
                return ResourceManager.GetString("NGC11_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINQ chain will be boxed.
        /// </summary>
        internal static string NGC11_Title {
            get {
                return ResourceManager.GetString("NGC11_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC12_Description {
            get {
                return ResourceManager.GetString("NGC12_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specific overload of Linq operator &apos;{0}&apos; is not implemented yet, the LINQ chain will be boxed at runtime to be able to use as an IEnumerable.
        /// </summary>
        internal static string NGC12_MessageFormat {
            get {
                return ResourceManager.GetString("NGC12_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This LINQ operator overload is not implemented.
        /// </summary>
        internal static string NGC12_Title {
            get {
                return ResourceManager.GetString("NGC12_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NGC20_Description {
            get {
                return ResourceManager.GetString("NGC20_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Borrow() should be called on &apos;{0}&apos; which is being passed by value.
        /// </summary>
        internal static string NGC20_MessageFormat {
            get {
                return ResourceManager.GetString("NGC20_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Borrow() should be called when passing by value.
        /// </summary>
        internal static string NGC20_Title {
            get {
                return ResourceManager.GetString("NGC20_Title", resourceCulture);
            }
        }
    }
}
