name: Benchmark

defaults:
  run:
    shell: pwsh   

on: workflow_dispatch

env:
  CICD: 1

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run benchmark
        run: .\scripts\RunBenchmarks.ps1

      - name: Generate benchmark result page
        run: .\scripts\GenBenchmarkPage.ps1

      - name: Upload benchmark result
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-result-page
          path: './artifacts/BenchmarkResultPage/**'

        
  publish-benchmark-result:
    needs: run-benchmark
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: benchmark-result-page
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
